# Generated by Django 5.2.15 on 2026-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_faqentry_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('source_type', models.CharField(choices=[('faq', 'FAQ entry'), ('course', 'Course'), ('lesson', 'Lesson'), ('doc', 'Help document')], max_length=16)),
                ('source_id', models.CharField(max_length=64)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English')], default='', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='assistant_k_source__7f80bb_idx')],
            },
        ),
    ]
