# Generated by Django 5.2.15 on 2026-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='audience',
            field=models.CharField(blank=True, choices=[('manager', 'Managers and admins'), ('admin', 'Admins only')], default='', max_length=16),
        ),
    ]
