# Generated by Django 5.2.15 on 2026-07-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_three_tier'),
        ('courses', '0003_course_issues_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(choices=[('open', 'Open (self-service catalog)'), ('general', 'General (auto-assigned to everyone)'), ('department', 'Department (auto-assigned to a department)')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Target department when audience is "department".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_courses', to='accounts.department'),
        ),
    ]
